# Generated by Django 5.0.11 on 2025-02-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_location', models.CharField(default='123 GreenField Road, AgriTech City, CA', max_length=255)),
                ('phone', models.CharField(default='+1 (800) 555-0199', max_length=20)),
                ('email', models.EmailField(default='support@smartagritech.com', max_length=254)),
                ('additional_info', models.TextField(blank=True, help_text='Optional extra details like support hours, alternative contact methods, or social media links.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
