# Generated by Django 5.0.11 on 2025-02-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About AI Farming', max_length=255)),
                ('mission_statement', models.TextField(help_text='Describe the mission of the platform.')),
                ('vision_statement', models.TextField(help_text='Describe the long-term vision.')),
                ('our_team', models.TextField(blank=True, help_text='Details about the team (Optional).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
