# Generated by Django 5.0.11 on 2025-02-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy Policy', max_length=255)),
                ('content', models.TextField(help_text='Enter the full privacy policy content.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
