# Generated by Django 5.0.11 on 2025-02-19 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_privacypolicy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='features',
        ),
        migrations.CreateModel(
            name='LandingPageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short feature title', max_length=255)),
                ('description', models.TextField(help_text='Detailed feature explanation')),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pages.landingpage')),
            ],
        ),
    ]
