# Generated by Django 5.0.11 on 2025-02-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_landingpage_features_landingpagefeature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
