# Generated by Django 5.0.11 on 2025-02-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_contactinfo_whatsapp_number_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(blank=True, default='+1 (800) 555-0199', max_length=20, null=True),
        ),
    ]
