# Generated by Django 5.0.11 on 2025-02-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='founder_bio',
            field=models.TextField(default='Founder bio will be updated soon.', help_text='Brief bio about the founder.'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='founder_image',
            field=models.ImageField(blank=True, help_text='Upload a picture of the founder.', null=True, upload_to='founder_images/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='founder_name',
            field=models.CharField(default='Rami Swaed', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='why_ai_farming',
            field=models.TextField(default='AI Farming leverages smart analytics, real-time monitoring, and machine learning to provide farmers with actionable insights, optimizing yield and sustainability.', help_text='Explain why AI Farming is important.'),
        ),
    ]
