# Generated by Django 5.0.11 on 2025-02-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_aboutpage_founder_bio_aboutpage_founder_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypolicy',
            name='content',
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='ai_data_usage',
            field=models.TextField(default='AI data is used solely for improving AI-driven insights and recommendations.', help_text='Describe how AI models use collected data.'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='contact_info',
            field=models.TextField(default='For any privacy-related concerns, contact us at support@yourdomain.com.', help_text='Provide contact details for privacy-related inquiries.'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='cookies_policy',
            field=models.TextField(default='We use cookies to improve user experience. By using our platform, you agree to our cookie policy.', help_text='Provide details about how cookies are used on the platform.'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='data_security',
            field=models.TextField(default='We implement encryption, access controls, and security best practices to safeguard user data.', help_text='Detail security measures taken to protect user data.'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='data_sharing',
            field=models.TextField(default='We do not sell user data. Some data may be shared with third-party APIs for enhanced AI predictions (e.g., weather data providers).', help_text='Describe if and when data is shared with third parties.'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='data_we_collect',
            field=models.TextField(default='We collect data such as user-provided farm details, environmental conditions, and usage data to enhance AI insights.', help_text='Describe the types of data collected.'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='how_we_use_data',
            field=models.TextField(default='The data collected is used to generate farming recommendations, improve AI models, and enhance user experience.', help_text='Explain how user data is used.'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='introduction',
            field=models.TextField(default='Welcome to AI Farming. Your privacy is important to us. This policy explains how we collect, use, and protect your information.', help_text='Introduction and overview of the privacy policy.'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='updates_policy',
            field=models.TextField(default='We may update this policy periodically. Users will be notified of major changes via email or platform notifications.', help_text='Explain how users will be notified about policy updates.'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='user_rights',
            field=models.TextField(default='Users have the right to access, modify, or delete their data. Requests can be made via our contact email.', help_text='Explain user rights regarding their data.'),
        ),
    ]
