# Generated by Django 5.0.11 on 2025-02-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_privacypolicy_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, help_text='SEO-friendly blog URL', unique=True),
        ),
    ]
