# Generated by Django 5.0.11 on 2025-02-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
