# Generated by Django 5.0.11 on 2025-02-26 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_testimonial_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='how_it_works',
        ),
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='✅', help_text='Example: 📍, 🤖, 📊', max_length=50)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pages.landingpage')),
            ],
        ),
    ]
