# Generated by Django 5.0.11 on 2025-02-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_remove_landingpage_how_it_works_howitworksstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='howitworksstep',
            name='border_color',
            field=models.CharField(choices=[('primary', 'Blue'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Yellow'), ('info', 'Light Blue')], default='primary', max_length=10),
        ),
    ]
