# Generated by Django 5.0.11 on 2025-02-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_howitworksstep_border_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Enter the question.', max_length=255)),
                ('answer', models.TextField(help_text='Provide the answer with formatting support.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance in the FAQ list.')),
                ('icon', models.CharField(default='❓', help_text='Emoji or icon to represent the question', max_length=50)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
