# Generated by Django 5.0.11 on 2025-02-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0003_remove_reportrequest_soil_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrequest',
            name='soil_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
