# Generated by Django 5.0.11 on 2025-02-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0004_reportrequest_soil_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrequest',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
