# Generated by Django 5.0.11 on 2025-02-21 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0005_reportrequest_fulfilled_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aireport',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monetization.payment'),
        ),
    ]
