# Generated by Django 5.0.11 on 2025-02-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0006_alter_aireport_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropSuitability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('crop_type', models.CharField(blank=True, max_length=100, null=True)),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('min_soil_temp', models.FloatField()),
                ('max_soil_temp', models.FloatField()),
                ('min_pH', models.FloatField()),
                ('max_pH', models.FloatField()),
                ('min_moisture', models.FloatField(blank=True, null=True)),
                ('max_moisture', models.FloatField(blank=True, null=True)),
                ('max_precipitation', models.FloatField()),
                ('min_nitrogen', models.FloatField(blank=True, null=True)),
                ('max_nitrogen', models.FloatField(blank=True, null=True)),
                ('min_phosphorus', models.FloatField(blank=True, null=True)),
                ('max_phosphorus', models.FloatField(blank=True, null=True)),
                ('min_potassium', models.FloatField(blank=True, null=True)),
                ('max_potassium', models.FloatField(blank=True, null=True)),
                ('preferred_growing_season', models.JSONField(blank=True, default=list, help_text='List of preferred months [1-12].')),
                ('suitable_soil_types', models.JSONField(blank=True, default=list, help_text='List of suitable soil types.')),
            ],
        ),
    ]
