# Generated by Django 5.0.11 on 2025-02-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0007_cropsuitability'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrequest',
            name='precipitation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportrequest',
            name='relative_humidity_2m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportrequest',
            name='temperature_2m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportrequest',
            name='wind_speed_10m',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
