# Generated by Django 5.0.11 on 2025-02-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0008_reportrequest_precipitation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropsuitability',
            name='max_moisture',
        ),
        migrations.RemoveField(
            model_name='cropsuitability',
            name='max_nitrogen',
        ),
        migrations.RemoveField(
            model_name='cropsuitability',
            name='max_pH',
        ),
        migrations.RemoveField(
            model_name='cropsuitability',
            name='max_phosphorus',
        ),
        migrations.RemoveField(
            model_name='cropsuitability',
            name='max_potassium',
        ),
        migrations.RemoveField(
            model_name='cropsuitability',
            name='max_precipitation',
        ),
        migrations.RemoveField(
            model_name='cropsuitability',
            name='max_soil_temp',
        ),
        migrations.RemoveField(
            model_name='cropsuitability',
            name='max_temp',
        ),
        migrations.RemoveField(
            model_name='cropsuitability',
            name='min_moisture',
        ),
        migrations.RemoveField(
            model_name='cropsuitability',
            name='min_nitrogen',
        ),
        migrations.RemoveField(
            model_name='cropsuitability',
            name='min_pH',
        ),
        migrations.RemoveField(
            model_name='cropsuitability',
            name='min_phosphorus',
        ),
        migrations.RemoveField(
            model_name='cropsuitability',
            name='min_potassium',
        ),
        migrations.RemoveField(
            model_name='cropsuitability',
            name='min_soil_temp',
        ),
        migrations.RemoveField(
            model_name='cropsuitability',
            name='min_temp',
        ),
        migrations.RemoveField(
            model_name='reportrequest',
            name='moisture',
        ),
        migrations.RemoveField(
            model_name='reportrequest',
            name='nitrogen',
        ),
        migrations.RemoveField(
            model_name='reportrequest',
            name='ph_level',
        ),
        migrations.RemoveField(
            model_name='reportrequest',
            name='phosphorus',
        ),
        migrations.RemoveField(
            model_name='reportrequest',
            name='potassium',
        ),
        migrations.RemoveField(
            model_name='reportrequest',
            name='precipitation',
        ),
        migrations.RemoveField(
            model_name='reportrequest',
            name='relative_humidity_2m',
        ),
        migrations.RemoveField(
            model_name='reportrequest',
            name='soil_temp_0_to_7cm',
        ),
        migrations.RemoveField(
            model_name='reportrequest',
            name='soil_temp_7_to_28cm',
        ),
        migrations.RemoveField(
            model_name='reportrequest',
            name='temperature_2m',
        ),
        migrations.RemoveField(
            model_name='reportrequest',
            name='wind_speed_10m',
        ),
        migrations.AddField(
            model_name='cropsuitability',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic crop suitability conditions (e.g., min_temp, max_pH).'),
        ),
        migrations.AddField(
            model_name='reportrequest',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic soil properties (e.g., pH, nitrogen, moisture).'),
        ),
        migrations.AddField(
            model_name='reportrequest',
            name='weather_data',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic weather data (e.g., temperature, humidity, wind speed).'),
        ),
        migrations.AlterField(
            model_name='cropsuitability',
            name='preferred_growing_season',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred growing months [1-12].'),
        ),
    ]
