# Generated by Django 5.0.11 on 2025-02-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0011_rename_active_coupon_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalconfig',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
