# Generated by Django 5.0.11 on 2025-02-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0012_paypalconfig_webhook_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('paused', 'Paused'), ('expired', 'Expired')], default='active', max_length=20),
        ),
    ]
