# Generated by Django 5.0.11 on 2025-02-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0013_alter_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration',
            field=models.CharField(choices=[('one_time', 'One-Time'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='one_time', max_length=10),
        ),
    ]
