# Generated by Django 5.0.11 on 2025-02-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0015_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='paypal_plan_id',
            field=models.CharField(blank=True, help_text='Enter the PayPal plan ID for this subscription plan.', max_length=255, null=True),
        ),
    ]
