# Generated by Django 5.0.11 on 2025-02-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0018_order_currency_order_discount_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('one_time', 'One-Time Purchase'), ('subscription', 'Subscription'), ('donation', 'Donation')], max_length=20),
        ),
    ]
