# Generated by Django 5.0.11 on 2025-02-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0019_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='orders_pdfs/'),
        ),
    ]
