# Generated by Django 5.0.11 on 2025-02-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0020_order_report_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
