# Generated by Django 5.0.11 on 2025-03-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0022_order_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrequest',
            name='report_data',
            field=models.JSONField(blank=True, default=dict, help_text='Processed data for PDF generation'),
        ),
    ]
