# Generated by Django 5.0.11 on 2025-03-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0024_donationorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationorder',
            name='order_type',
            field=models.CharField(choices=[('donation', 'Donation')], default='donation', max_length=20),
        ),
    ]
