# Generated by Django 5.0.11 on 2025-03-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeAdminAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FakeAdminAttempt',
        ),
    ]
