# Generated by Django 5.0.11 on 2025-02-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('original_location', models.CharField(blank=True, max_length=100, null=True)),
                ('temperature_2m', models.FloatField()),
                ('relative_humidity_2m', models.FloatField()),
                ('wind_speed_10m', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
