# Generated by Django 5.0.11 on 2025-02-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'ordering': ['-last_updated', '-time']},
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='location',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['location', 'time'], name='weather_wea_locatio_1afa99_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['-last_updated', '-time'], name='weather_wea_last_up_7b8890_idx'),
        ),
    ]
