# Generated by Django 5.0.11 on 2025-02-08 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soil', '0004_soildata_sensor_id_soildata_sensor_type_and_more'),
        ('weather', '0002_alter_weatherdata_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('max_precipitation', models.FloatField(default=50.0)),
                ('min_soil_temp', models.FloatField(default=10.0)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_crops', models.JSONField(help_text='AI-recommended crops based on soil & weather conditions.')),
                ('expected_yield', models.FloatField(blank=True, help_text='Predicted yield in kg/ha.', null=True)),
                ('risk_assessment', models.TextField(blank=True, help_text='Warnings for drought, frost, or other risks.', null=True)),
                ('optimal_planting_time', models.CharField(help_text='Best planting window: Early, Mid, Late Season.', max_length=50)),
                ('ai_model_version', models.CharField(help_text='AI model version used for this recommendation.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='recommendations.crop')),
                ('soil_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='soil.soildata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
                ('weather_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='weather.weatherdata')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='recommendat_user_id_39fd0b_idx'), models.Index(fields=['soil_data'], name='recommendat_soil_da_1f8121_idx'), models.Index(fields=['weather_data'], name='recommendat_weather_817446_idx'), models.Index(fields=['-created_at'], name='recommendat_created_ca71b7_idx')],
            },
        ),
    ]
