# Generated by Django 5.0.11 on 2025-02-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='preferred_growing_season',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred months [1-12].'),
        ),
    ]
