# Generated by Django 5.0.11 on 2025-02-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_recommendation_alerts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='ai_model_version',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamically fetched AI model versions.'),
        ),
    ]
