# Generated by Django 5.0.11 on 2025-02-14 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_alter_recommendation_ai_model_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='ai_model_version',
        ),
    ]
