# Generated by Django 5.0.11 on 2025-02-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('original_location', models.CharField(blank=True, max_length=100, null=True)),
                ('soil_temp_0_to_7cm', models.FloatField()),
                ('soil_temp_7_to_28cm', models.FloatField()),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
            ],
        ),
    ]
