# Generated by Django 5.0.11 on 2025-02-06 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0002_alter_soildata_options_soildata_last_updated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='soildata',
            name='data_source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('csv', 'CSV Upload'), ('api', 'Weather API'), ('sensor', 'IoT Sensor')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='soildata',
            name='moisture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='nitrogen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='ph_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='phosphorus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='potassium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soil_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='soildata',
            index=models.Index(fields=['user'], name='soil_soilda_user_id_7dd22a_idx'),
        ),
    ]
