# Generated by Django 5.0.11 on 2025-02-06 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0003_soildata_data_source_soildata_moisture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='soildata',
            name='sensor_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='sensor_type',
            field=models.CharField(blank=True, choices=[('temperature', 'Temperature Sensor'), ('moisture', 'Moisture Sensor'), ('ph', 'pH Sensor'), ('nutrients', 'NPK Sensor'), ('multi', 'Multi-Sensor Device')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='soildata',
            name='soil_temp_0_to_7cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soildata',
            name='soil_temp_7_to_28cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='soildata',
            index=models.Index(fields=['sensor_type'], name='soil_soilda_sensor__2a4b65_idx'),
        ),
        migrations.AddIndex(
            model_name='soildata',
            index=models.Index(fields=['sensor_id'], name='soil_soilda_sensor__00c907_idx'),
        ),
    ]
